# Generated by Django 2.2.7 on 2019-11-10 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='art',
            old_name='release_date',
            new_name='date',
        ),
    ]
