# Generated by Django 2.2.7 on 2019-11-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20191110_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='type',
            field=models.CharField(choices=[('p', 'Painting'), ('m', 'Music'), ('f', 'Film'), ('d', 'Digital')], max_length=1),
        ),
    ]
